name: IDF Spokesperson Bot
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run IDF Bot
        run: python idf_scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "IDF-Bot"
          git config --global user.email "bot@kodkodnews.co.il"
          git add content/news/*.md
          git commit -m "מבזק אוטומטי מדובר צהל" || exit 0
          git push
